apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gce-pd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer

---
#Zonal StorageClass for fsType ntfs
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: csi-gce-pd-ntfs
# provisioner: pd.csi.storage.gke.io
# parameters:
#   type: pd-standard
#   csi.storage.k8s.io/fstype: ntfs
# volumeBindingMode: WaitForFirstConsumer
